OBJS=conductor.o conductor_rectangle.o conductor_circle.o

# Object libraries
$(LIBINJ) : $(OBJS)
	- /bin/rm -f $(LIBINJ)
	- ar qc $(LIBINJ) $(OBJS)
	- ranlib $(LIBINJ)

# Clean up the directory
clean :
	/bin/rm -f *.o

distclean :
	/bin/rm -f *.o *.a

.cpp.o :
	$(CXX) $(CFLAGS) $(INCLUDES) $(MKLINC) $(MKLINCOPTS) -c $<
